# azerty-layout
keycode  65 = a
keycode  66 = b
keycode  67 = c
keycode  68 = d
keycode  69 = e
keycode  70 = f
keycode  71 = g
keycode  72 = h
keycode  73 = i
keycode  74 = j
#
keycode  75 = k
keycode  76 = l
keycode  77 = m
keycode  78 = n
keycode  79 = o
keycode  80 = p
keycode  81 = q
keycode  82 = r
keycode  83 = s
keycode  84 = t
#
keycode  85 = u
keycode  86 = v
keycode  192 = w
keycode  88 = x
keycode  89 = y
keycode  90 = z
#
